### ISSUE TITLE
Delay in confirming seed-phrase

### ISSUE THREAD

**Issue by EricAurel** [Concordium/concordium-wallet#18] opened 2023-11-21 14:22 UTC
**Bug Description**
After downloading the app and writing down the 24 seed words, I have to swipe or press the right seed word from a list. When doing that, a word in the line above or below is instead selected.
Overall, this function runs slow and with a lag.

**Steps to Reproduce**
**Expected Result**
**Actual Result**

**Versions**
App Version 1.3.0
IPhone 13 Mini

**Comment by ali-concordium** [comment] 2023-11-22 08:32
Hi Eric

Thank you for letting us know. I couldn't reproduce the issue you're experiencing. 

However, we're working on a new version of the iOS wallet, which will be released in the 2024. I can't give an exact date yet, but rest assured this issue will be addressed. 

If you continue to experience other features of the wallet, which runs slow or with lag, please check the following:
- Ensure that your iOS device is running the latest version of the operating system.
- Ensure that your device has enough free storage space. Being low on storage, can impact the performance of apps.
- Close any unnecessary apps running in the background. 
- Restart the device.

If it remains unresolved, please open a new issue, and refer to this one. 

Thank you.

**Closed** 2023-11-22 13:03 UTC
